### ISSUE TITLE
Feature Request -  Start with Lorem ipsum flag

### ISSUE THREAD

**Issue by meeple142** [lkcampbell/brackets-lorem-ipsum#10]
It would be nice to have the option of setting a flag that would make the string always start with Lorem ipsum. Just as a sign to others. I don't even care if the Latin makes sense after those two words - i don't read Latin but maybe you do :) Any way it would be nice.

Thanks again

**Comment by lkcampbell** [comment]
@meeple142, a preference to make all strings start with `Lorem Ipsum` is easy. A preference to use to original Lorem Ipsum code over and over is less easy, since I designed this extension to be completely random from the ground up. Still doable though.

Can you tell me what the phrase Lorem ipsum at the beginning of the text is important? Or why the original Lorem ipsum text is important? Purely from a design perspective I mean. I'm not a designer so I am curious to know.

**Comment by lkcampbell** [comment]
@meeple142, added a new `_orig` option to version 1.2.0 to address this feature request. I didn't get any feedback from you recently so I had to take my best guess on how to implement it. Hopefully, this will be sufficient for your needs.
